### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by CyclopDog**
Couldn't do all the methods, for some reason the my_map method is returning a error I cannot understand.
Why doesn't it get the multiply done in the block?

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Good start.
`my_each`, `my_count` and `my_map` isn't working as expected.
 - `my_each` is returning `nil`
 - `my_count` returns wrong answer for block
 - `my_map` returns `undefinded method error` for `[1,2,3].my_map { |i| i + 1 })`

Once updated, kindly resubmit for review. If more info required, don't hesitate to reach me on slack.

**Comment by CyclopDog** [comment]
Greetings inhaq, thank you for your feedback
When running the tests, what I get is what is in the image below, seems to be working fine in my terminal.
Could I get further information on the errors please?

image

**Comment by inhaq** [comment]
Hi @DevMFernandes 

 - `[1,2,3,4,5].my_each { |i| i }` should return `[1,2,3,4,5]` whereas it returns `nil`
 - `[1,2,3,4,5].my_count { |i| i > 4 })` returns 5 whereas it should return 1
 - `my_map` shows `undefined method `+' for nil:NilClass` for `[1,2,3].my_map { |i| i + 1 }`

Hope it'll help.

**Review by inhaq — CHANGES_REQUESTED** [review]
Good work on fixing several issues.
One last fix required and you're done.
 - `my_count` should work without block as well. Let's say, `[1,2,3].my_count` should return 3.

Once fixed, kindly resubmit for review. If needs help, don't hesitate to reach me on slack.

**Review by inhaq — APPROVED** [review]
Great work. You did it, it's 👍🏻
Good luck with the next project

**Pull request merged**
